import { describe, it, expect, vi } from 'vitest'
import { readFileSync } from 'node:fs'

// Conformance against the canonical address table in proxy/ssrf-vectors.json.
//
// The same policy is implemented across three GLANCE repositories, separately
// on purpose (this shared guard, plain ESM copied into a Docker image in
// dayGLANCE, strict TypeScript in its Electron bundle). A range added to one
// and forgotten in another is the drift that produced divergent copies of this
// logic to begin with, so each repo commits the same vectors file and checks
// its own implementation against it. Same idea as dayDial.vectors.json keeping
// the JS and Swift dial geometry in agreement.
//
// The file is generated by scripts/export-ssrf-vectors.mjs in krelltunez/
// dayGLANCE and copied here verbatim. Do not hand-edit it: change the policy
// there, regenerate, copy, and run this suite.
//
// If this fails, do not relax it. Either this repo's implementation drifted, or
// the table changed and this copy is stale.

const vectorFile = JSON.parse(readFileSync('proxy/ssrf-vectors.json', 'utf-8'))
const vectors = vectorFile.vectors

// Resolution is stubbed per case so the guard sees the exact vector address.
// Feeding literals through a URL instead would not work: the WHATWG parser
// rewrites IPv4-mapped v6 literals (::ffff:127.0.0.1 becomes ::ffff:7f00:1), so
// several vectors would never reach the classifier in the form they name.
//
// The module is mocked rather than spied on because ssrfGuard.js captures
// dns.promises.lookup in a module-level const, which a spy installed after
// import cannot replace.
let resolved = []
vi.mock('dns', async importOriginal => {
  const real = await importOriginal()
  return { ...real, default: { ...real.default, promises: { lookup: async () => resolved } } }
})

const { assertSafeUrl, SsrfError } = await import('./ssrfGuard.js')

async function verdict(allowPrivate) {
  try {
    await assertSafeUrl('https://target.example.com/dav/', { allowPrivate })
    return 'allow'
  } catch (err) {
    if (err instanceof SsrfError) return 'deny'
    throw err
  }
}

describe('ssrf-vectors.json', () => {
  it('is the shape this suite expects', () => {
    expect(vectorFile.version).toBe(1)
    expect(vectorFile.postures).toEqual({
      hosted: { allowPrivate: false, description: 'a shared cloud deployment' },
      selfHost: { allowPrivate: true, description: "an instance on the operator's own network" },
    })
    expect(vectors.length).toBeGreaterThan(40)
    expect([...new Set(vectors.map(v => v.class))].sort()).toEqual(['always', 'ok', 'private'])
  })
})

describe('assertSafeUrl produces the table verdict in both postures', () => {
  it.each(vectors.map(v => [v.address, v.family, v.hosted, v.note]))(
    'hosted: %s (%s) -> %s: %s',
    async (address, family, expected) => {
      resolved = [{ address, family }]
      expect(await verdict(false)).toBe(expected)
    },
  )

  it.each(vectors.map(v => [v.address, v.family, v.selfHost, v.note]))(
    'self-host: %s (%s) -> %s: %s',
    async (address, family, expected) => {
      resolved = [{ address, family }]
      expect(await verdict(true)).toBe(expected)
    },
  )
})
